[package]
name = "pid1-exe"
version = "0.1.6"
edition = "2021"
description = "A Unix PID1 process wrapper for signal handling and zombie reaping"
readme = "../README.md"
homepage = "https://github.com/fpco/pid1-rs"
repository = "https://github.com/fpco/pid1-rs"
license = "MIT"
keywords = ["cli", "init", "pid1", "process"]
categories = ["command-line-utilities"]

[[bin]]
name = "pid1"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.41", default-features = false, features = [
  "derive",
  "help",
  "std",
] }
pid1 = { version = "0.1.6", path = "../pid1" }
signal-hook = "0.4.3"
